### ISSUE TITLE
Bug: Typescript error when using authentication

### ISSUE THREAD

**Issue by mgm1313** [LuvDaSun/Skiffa#109]
I created a minimal reproduction, you can see the TS error on this line: https://github.com/mgm1313/SkiffaExamples/blob/bug/register-operation-handlers/packages/npm/reverse/src/server.ts#L19

**Comment by elmerbulthuis** [comment]
check out -> https://github.com/mgm1313/SkiffaExamples/pull/1 <-

So the authorizatoin model should be the same on the handlers and the server! then it works

**Comment by mgm1313** [comment]
Makes sense, thanks!
